//! Iac E2E tests.
//!
//! End-to-end tests for iac feature.
//! Generated by `rsc scaffold routes`

use rustscript::test::*;

#[e2e]
fn iac_overview_page_loads() {
    navigate("/iac");
    assert_url_contains("iac");
    assert_no_errors();
}

#[e2e]
fn iac_navigation_works() {
    navigate("/iac");
    assert_element_exists(".iac-page, .iac-layout");
    assert_no_errors();
}
