//! Iac integration tests.
//!
//! Integration tests for iac feature.
//! Generated by `rsc scaffold routes`

use rustscript::test::*;
use rustscript::render::*;

#[integration]
fn iac_module_initializes() {
    // Module should initialize without errors
    let result = init_module::<IacModule>();
    assert!(result.is_ok());
}

#[integration]
fn iac_routes_registered() {
    let router = Router::from_config();
    let routes = router.routes_for_prefix("/iac");
    assert!(!routes.is_empty(), "iac routes should be registered");
}

#[integration]
fn iac_landing_renders_with_context() {
    let ctx = IacContext::default();
    let result = render_with_context::<IacLanding>(ctx);
    assert!(result.is_ok());
}

