//! Compilation integration tests.
//!
//! Tests that all components compile and render correctly.
//! Generated by `rsc scaffold routes`

use rustscript::test::*;
use rustscript::render::*;

#[integration]
fn app_component_compiles() {
    // App component should compile without errors
    let result = compile_component::<App>();
    assert!(result.is_ok());
}

#[integration]
fn layout_component_compiles() {
    let result = compile_component::<Layout>();
    assert!(result.is_ok());
}

#[integration]
fn dashboard_component_compiles() {
    let result = compile_component::<Dashboard>();
    assert!(result.is_ok(), "Dashboard should compile");
}

#[integration]
fn cloudemu_overview_component_compiles() {
    let result = compile_component::<CloudemuOverview>();
    assert!(result.is_ok(), "CloudemuOverview should compile");
}

#[integration]
fn cloudkit_overview_component_compiles() {
    let result = compile_component::<CloudkitOverview>();
    assert!(result.is_ok(), "CloudkitOverview should compile");
}

#[integration]
fn iac_overview_component_compiles() {
    let result = compile_component::<IacOverview>();
    assert!(result.is_ok(), "IacOverview should compile");
}

#[integration]
fn workflow_runner_component_compiles() {
    let result = compile_component::<WorkflowRunner>();
    assert!(result.is_ok(), "WorkflowRunner should compile");
}

#[integration]
fn settings_index_component_compiles() {
    let result = compile_component::<SettingsIndex>();
    assert!(result.is_ok(), "SettingsIndex should compile");
}

#[integration]
fn not_found_component_compiles() {
    let result = compile_component::<NotFound>();
    assert!(result.is_ok(), "NotFound should compile");
}

