//! Context provider integration tests.
//!
//! Tests context providers work correctly across the app.
//! Generated by `rsc scaffold routes`

use rustscript::test::*;
use rustscript::context::*;

#[integration]
fn provider_context_initializes() {
    let ctx = ProviderContext::default();
    assert!(ctx.current().is_some() || ctx.providers().len() > 0);
}

#[integration]
fn environment_context_initializes() {
    let ctx = EnvironmentContext::default();
    assert!(ctx.current().is_some());
}

#[integration]
fn auth_context_initializes() {
    let ctx = AuthContext::default();
    // Auth context should initialize without panic
    let _ = ctx.is_authenticated();
}

#[integration]
fn theme_context_initializes() {
    let ctx = ThemeContext::default();
    assert!(ctx.current_theme().is_some());
}

#[integration]
fn context_providers_are_independent() {
    // Each context should work independently
    let provider_ctx = ProviderContext::default();
    let env_ctx = EnvironmentContext::default();

    // Changing one shouldn't affect the other
    assert!(provider_ctx.current() != env_ctx.current());
}

#[integration]
fn context_updates_propagate() {
    let (ctx, set_ctx) = use_state(ProviderContext::default());

    // Update should work
    set_ctx(|c| c.set_provider("aws"));

    // Note: In real test, would verify propagation
}
