//! E2E layout tests.
//!
//! Tests page layout structure and rendering.
//! Generated by `rsc scaffold routes`

use rustscript::test::*;

#[e2e]
fn app_loads_with_complete_layout() {
    navigate("/");
    assert_element_exists("header");
    assert_element_exists("main");
    assert_no_errors();
}

#[e2e]
fn header_renders_correctly() {
    navigate("/");
    assert_element_exists(".header");
    assert_element_exists(".brand");
    assert_element_exists(".search-input");
}

#[e2e]
fn navigation_menu_renders() {
    navigate("/");
    assert_element_exists("nav");
}

