//! E2E navigation tests.
//!
//! Tests browser navigation behavior across routes.
//! Generated by `rsc scaffold routes`

use rustscript::test::*;

#[e2e]
fn brand_click_returns_to_landing() {
    navigate("/settings");
    click(".brand-link");
    assert_url("/");
}

#[e2e]
fn browser_back_button_works() {
    navigate("/");
    navigate("/settings");
    browser_back();
    assert_url("/");
}

#[e2e]
fn browser_forward_button_works() {
    navigate("/");
    navigate("/settings");
    browser_back();
    browser_forward();
    assert_url("/settings");
}

#[e2e]
fn unknown_route_shows_404() {
    navigate("/nonexistent-page-12345");
    assert_element_exists(".not-found");
}
