//! E2E routing tests.
//!
//! Tests route loading and parameter handling.
//! Generated by `rsc scaffold routes`

use rustscript::test::*;

#[e2e]
fn dashboard_route_loads() {
    navigate("/");
    assert_url("/");
    assert_no_errors();
}

#[e2e]
fn cloudemu_overview_route_loads() {
    navigate("/cloudemu");
    assert_url("/cloudemu");
    assert_no_errors();
}

#[e2e]
fn cloudkit_overview_route_loads() {
    navigate("/cloudkit");
    assert_url("/cloudkit");
    assert_no_errors();
}

#[e2e]
fn iac_overview_route_loads() {
    navigate("/iac");
    assert_url("/iac");
    assert_no_errors();
}

#[e2e]
fn settings_index_route_loads() {
    navigate("/settings");
    assert_url("/settings");
    assert_no_errors();
}

#[e2e]
fn not_found_route_loads() {
    navigate("*");
    assert_url("*");
    assert_no_errors();
}

