//! Settings Pages Tests
//!
//! Generated by `rsc scaffold routes`

use rsc::test::*;

// ============================================================================
// SETTINGS INDEX PAGE TESTS
// ============================================================================

#[test]
fn settings_index_renders_without_error() {
    let result = render! {
        TestContextProvider {
            SettingsIndexPage()
        }
    };
    assert!(result.is_ok());
}

#[test]
fn settings_index_displays_title() {
    let rendered = render! {
        TestContextProvider {
            SettingsIndexPage()
        }
    };
    assert!(rendered.contains_text("Settings"));
}

#[test]
fn settings_index_requires_auth() {
    // Settings should require authentication
    let rendered = render_without_auth! {
        SettingsIndexPage()
    };
    // Should redirect or show login prompt
    assert!(rendered.is_ok());
}

// ============================================================================
// SETTINGS NAV COMPONENT TESTS
// ============================================================================

#[test]
fn settings_nav_renders() {
    let rendered = render! {
        SettingsNav()
    };
    assert!(rendered.query_selector(".component, nav").is_some());
}

#[test]
fn settings_nav_has_providers_link() {
    let rendered = render! {
        SettingsNav()
    };
    let link = rendered.query_selector("a[href='/settings/providers']");
    assert!(link.is_some());
}

#[test]
fn settings_nav_has_endpoints_link() {
    let rendered = render! {
        SettingsNav()
    };
    let link = rendered.query_selector("a[href='/settings/endpoints']");
    assert!(link.is_some());
}

#[test]
fn settings_nav_has_credentials_link() {
    let rendered = render! {
        SettingsNav()
    };
    let link = rendered.query_selector("a[href='/settings/credentials']");
    assert!(link.is_some());
}

#[test]
fn settings_nav_has_users_link() {
    let rendered = render! {
        SettingsNav()
    };
    let link = rendered.query_selector("a[href='/settings/users']");
    assert!(link.is_some());
}

// ============================================================================
// PROVIDERS SETTINGS TESTS
// ============================================================================

#[test]
fn settings_providers_renders() {
    let result = render! {
        TestContextProvider {
            SettingsProvidersPage()
        }
    };
    assert!(result.is_ok());
}

#[test]
fn provider_config_list_renders() {
    let rendered = render! {
        TestContextProvider {
            ProviderConfigList()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn provider_config_list_shows_providers() {
    let rendered = render_with_mock! {
        data: [
            { id: "aws", name: "AWS", enabled: true },
            { id: "azure", name: "Azure", enabled: false },
        ],
        ProviderConfigList()
    };
    let items = rendered.query_selector_all("li, .provider-item");
    assert!(items.len() >= 2);
}

#[test]
fn provider_config_form_renders() {
    let rendered = render! {
        TestContextProvider {
            ProviderConfigForm()
        }
    };
    assert!(rendered.query_selector("form, .form-container").is_some());
}

// ============================================================================
// ENDPOINTS SETTINGS TESTS
// ============================================================================

#[test]
fn settings_endpoints_renders() {
    let result = render! {
        TestContextProvider {
            SettingsEndpointsPage()
        }
    };
    assert!(result.is_ok());
}

#[test]
fn endpoint_list_renders() {
    let rendered = render! {
        TestContextProvider {
            EndpointList()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn endpoint_list_shows_endpoints() {
    let rendered = render_with_mock! {
        data: [
            { id: "local", name: "LocalStack", url: "http://localhost:4566" },
            { id: "aws", name: "AWS", url: "https://aws.amazon.com" },
        ],
        EndpointList()
    };
    let items = rendered.query_selector_all("li, .endpoint-item");
    assert!(items.len() >= 2);
}

#[test]
fn endpoint_form_renders() {
    let rendered = render! {
        TestContextProvider {
            EndpointForm()
        }
    };
    assert!(rendered.query_selector("form, .form-container").is_some());
}

#[test]
fn endpoint_form_has_url_input() {
    let rendered = render! {
        TestContextProvider {
            EndpointForm()
        }
    };
    let url_input = rendered.query_selector("input[name='url'], input[type='url']");
    assert!(url_input.is_some());
}

// ============================================================================
// CREDENTIALS SETTINGS TESTS
// ============================================================================

#[test]
fn settings_credentials_renders() {
    let result = render! {
        TestContextProvider {
            SettingsCredentialsPage()
        }
    };
    assert!(result.is_ok());
}

#[test]
fn credential_list_renders() {
    let rendered = render! {
        TestContextProvider {
            CredentialList()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn credential_list_masks_sensitive_data() {
    let rendered = render_with_mock! {
        data: [
            { id: "aws-main", name: "AWS Main", accessKey: "AKIA..." },
        ],
        CredentialList()
    };
    // Should not show full access key
    assert!(!rendered.contains_text("AKIA123456") || rendered.contains_text("***"));
}

#[test]
fn add_credential_modal_renders() {
    let rendered = render! {
        AddCredentialModal()
    };
    assert!(rendered.is_ok());
}

#[test]
fn add_credential_modal_has_form_fields() {
    let rendered = render_with_state! {
        is_open: true,
        AddCredentialModal()
    };
    let inputs = rendered.query_selector_all("input, select");
    assert!(inputs.len() > 0);
}

// ============================================================================
// USERS SETTINGS TESTS
// ============================================================================

#[test]
fn settings_users_renders() {
    let result = render! {
        TestContextProvider {
            SettingsUsersPage()
        }
    };
    assert!(result.is_ok());
}

#[test]
fn user_list_renders() {
    let rendered = render! {
        TestContextProvider {
            UserList()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn user_list_shows_users() {
    let rendered = render_with_mock! {
        data: [
            { id: "1", name: "John Doe", email: "john@example.com", role: "admin" },
            { id: "2", name: "Jane Smith", email: "jane@example.com", role: "developer" },
        ],
        UserList()
    };
    let items = rendered.query_selector_all("li, .user-item, tr");
    assert!(items.len() >= 2);
}

#[test]
fn user_form_renders() {
    let rendered = render! {
        TestContextProvider {
            UserForm()
        }
    };
    assert!(rendered.query_selector("form, .form-container").is_some());
}

#[test]
fn user_form_has_role_selector() {
    let rendered = render! {
        TestContextProvider {
            UserForm()
        }
    };
    let role = rendered.query_selector("select[name='role']");
    assert!(role.is_some() || rendered.contains_text("Role"));
}

// ============================================================================
// HELPER
// ============================================================================

#[component]
fn TestContextProvider(children: Children) -> Element {
    use @modules::context::AppContextProvider;
    rsx! { AppContextProvider { {children} } }
}
