//! CloudKit Operations Page Tests
//!
//! Generated by `rsc scaffold routes`

use rsc::test::*;

// ============================================================================
// PAGE RENDER TESTS
// ============================================================================

#[test]
fn cloudkit_operations_renders_without_error() {
    let result = render! {
        TestContextProvider {
            CloudkitOperationsPage()
        }
    };
    assert!(result.is_ok());
}

#[test]
fn cloudkit_operations_displays_title() {
    let rendered = render! {
        TestContextProvider {
            CloudkitOperationsPage()
        }
    };
    assert!(rendered.contains_text("Operations"));
}

// ============================================================================
// OPERATIONS LIST COMPONENT TESTS
// ============================================================================

#[test]
fn operations_list_renders() {
    let rendered = render! {
        TestContextProvider {
            OperationsList()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn operations_list_shows_loading() {
    let rendered = render! {
        TestContextProvider {
            OperationsList()
        }
    };
    assert!(rendered.contains_text("Loading") || rendered.query_selector(".loading").is_some());
}

#[test]
fn operations_list_displays_operations() {
    let rendered = render_with_mock! {
        data: [
            { id: "CreateBucket", service: "S3", description: "Create a bucket" },
            { id: "PutItem", service: "DynamoDB", description: "Put an item" },
        ],
        OperationsList()
    };
    let items = rendered.query_selector_all("li, .operation-item");
    assert!(items.len() >= 2);
}

#[test]
fn operations_list_items_are_selectable() {
    let rendered = render_with_mock! {
        data: [{ id: "CreateBucket", service: "S3" }],
        OperationsList()
    };
    let clickable = rendered.query_selector_all("button, [role='button'], a");
    assert!(clickable.len() > 0);
}

// ============================================================================
// OPERATION RUNNER COMPONENT TESTS
// ============================================================================

#[test]
fn operation_runner_renders() {
    let rendered = render! {
        TestContextProvider {
            OperationRunner()
        }
    };
    assert!(rendered.query_selector(".container").is_some());
}

#[test]
fn operation_runner_has_parameter_inputs() {
    let rendered = render_with_mock! {
        operation: { id: "CreateBucket", params: ["BucketName", "Region"] },
        OperationRunner()
    };
    let inputs = rendered.query_selector_all("input, select");
    assert!(inputs.len() > 0);
}

#[test]
fn operation_runner_has_execute_button() {
    let rendered = render! {
        TestContextProvider {
            OperationRunner()
        }
    };
    let execute = rendered.query_selector("button.execute, button[type='submit']");
    assert!(execute.is_some() || rendered.contains_text("Execute") || rendered.contains_text("Run"));
}

// ============================================================================
// OPERATION HISTORY COMPONENT TESTS
// ============================================================================

#[test]
fn operation_history_renders() {
    let rendered = render! {
        TestContextProvider {
            OperationHistory()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn operation_history_displays_past_operations() {
    let rendered = render_with_mock! {
        data: [
            { id: "1", operation: "CreateBucket", status: "success", timestamp: "2024-01-15T10:00:00Z" },
            { id: "2", operation: "PutItem", status: "error", timestamp: "2024-01-15T09:00:00Z" },
        ],
        OperationHistory()
    };
    let items = rendered.query_selector_all("li, .history-item");
    assert!(items.len() >= 2);
}

#[test]
fn operation_history_shows_status() {
    let rendered = render_with_mock! {
        data: [{ id: "1", operation: "CreateBucket", status: "success" }],
        OperationHistory()
    };
    assert!(rendered.contains_text("success") || rendered.query_selector(".status-success").is_some());
}

// ============================================================================
// HELPER
// ============================================================================

#[component]
fn TestContextProvider(children: Children) -> Element {
    use @modules::context::AppContextProvider;
    rsx! { AppContextProvider { {children} } }
}
