//! Mock clients for testing.
//!
//! Generated by `rsc scaffold services`

pub mod storage_mock;
pub use storage_mock::StorageClientMock;
pub mod functions_mock;
pub use functions_mock::FunctionsClientMock;
pub mod pubsub_mock;
pub use pubsub_mock::PubsubClientMock;
