//! Gcp API clients.
//!
//! Generated by `rsc scaffold services`

use rustscript::prelude::*;
use super::api_base;

pub mod storage;
pub mod functions;
pub mod pubsub;

pub use storage::StorageClient;
pub use functions::FunctionsClient;
pub use pubsub::PubsubClient;
