//! API client tests.
//!
//! Tests API client configuration and basic functionality.
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use rustscript::http::*;
use crate::api::*;

#[test]
fn api_base_returns_valid_url() {
    let base = api_base();
    assert!(!base.is_empty());
    assert!(base.starts_with("http"));
}

#[test]
fn current_provider_returns_valid_id() {
    let provider = current_provider();
    assert!(!provider.is_empty());
}

#[tokio::test]
async fn api_client_can_be_created() {
    let client = Client::new();
    assert!(client.is_ready().await);
}

#[tokio::test]
async fn api_client_handles_timeout() {
    let client = Client::builder()
        .timeout(std::time::Duration::from_millis(100))
        .build();

    // Should handle timeout gracefully
    let result = client.get("http://httpbin.org/delay/10").send().await;
    assert!(result.is_err());
}

#[tokio::test]
async fn api_client_retries_on_failure() {
    let client = Client::builder()
        .retry(3)
        .build();

    // Client should be configured with retries
    assert!(client.config().retry_count >= 3);
}
