//! HTTP client tests.
//!
//! Tests HTTP client functionality and error handling.
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use rustscript::http::*;

#[tokio::test]
async fn http_get_request() {
    let client = Client::new();
    let response = client.get("https://httpbin.org/get")
        .send()
        .await;

    assert!(response.is_ok());
    assert_eq!(response.unwrap().status(), 200);
}

#[tokio::test]
async fn http_post_request() {
    let client = Client::new();
    let response = client.post("https://httpbin.org/post")
        .json(&serde_json::json!({"test": "data"}))
        .send()
        .await;

    assert!(response.is_ok());
}

#[tokio::test]
async fn http_handles_404() {
    let client = Client::new();
    let response = client.get("https://httpbin.org/status/404")
        .send()
        .await;

    assert!(response.is_ok());
    assert_eq!(response.unwrap().status(), 404);
}

#[tokio::test]
async fn http_handles_500() {
    let client = Client::new();
    let response = client.get("https://httpbin.org/status/500")
        .send()
        .await;

    assert!(response.is_ok());
    assert_eq!(response.unwrap().status(), 500);
}

#[test]
fn request_builder_sets_headers() {
    let request = Request::get("https://example.com")
        .header("Authorization", "Bearer token")
        .header("Content-Type", "application/json")
        .build();

    assert!(request.headers().contains_key("Authorization"));
    assert!(request.headers().contains_key("Content-Type"));
}

#[test]
fn request_builder_sets_query_params() {
    let request = Request::get("https://example.com")
        .query("page", "1")
        .query("limit", "10")
        .build();

    assert!(request.url().contains("page=1"));
    assert!(request.url().contains("limit=10"));
}
