//! CloudKit API Explorer Page Tests
//!
//! Generated by `rsc scaffold routes`

use rsc::test::*;

// ============================================================================
// PAGE RENDER TESTS
// ============================================================================

#[test]
fn cloudkit_explorer_renders_without_error() {
    let result = render! {
        TestContextProvider {
            CloudkitExplorerPage()
        }
    };
    assert!(result.is_ok());
}

#[test]
fn cloudkit_explorer_displays_title() {
    let rendered = render! {
        TestContextProvider {
            CloudkitExplorerPage()
        }
    };
    assert!(rendered.contains_text("Explorer") || rendered.contains_text("API"));
}

// ============================================================================
// API TREE COMPONENT TESTS
// ============================================================================

#[test]
fn api_tree_renders() {
    let rendered = render! {
        TestContextProvider {
            ApiTree()
        }
    };
    assert!(rendered.query_selector(".container").is_some());
}

#[test]
fn api_tree_shows_providers() {
    let rendered = render! {
        TestContextProvider {
            ApiTree()
        }
    };
    assert!(rendered.contains_text("AWS") ||
            rendered.contains_text("Azure") ||
            rendered.contains_text("GCP"));
}

#[test]
fn api_tree_shows_services() {
    let rendered = render_with_context! {
        provider: "aws",
        ApiTree()
    };
    assert!(rendered.contains_text("S3") ||
            rendered.contains_text("DynamoDB") ||
            rendered.contains_text("Lambda"));
}

#[test]
fn api_tree_is_expandable() {
    let rendered = render! {
        TestContextProvider {
            ApiTree()
        }
    };
    let expand_buttons = rendered.query_selector_all("button.expand, [data-expandable]");
    assert!(expand_buttons.len() > 0 || rendered.contains_text("▶") || rendered.contains_text("▼"));
}

// ============================================================================
// REQUEST BUILDER COMPONENT TESTS
// ============================================================================

#[test]
fn request_builder_renders() {
    let rendered = render! {
        TestContextProvider {
            RequestBuilder()
        }
    };
    assert!(rendered.query_selector("form, .form-container").is_some());
}

#[test]
fn request_builder_has_method_selector() {
    let rendered = render! {
        TestContextProvider {
            RequestBuilder()
        }
    };
    let method = rendered.query_selector("select[name='method'], input[name='method']");
    assert!(method.is_some() || rendered.contains_text("GET") || rendered.contains_text("POST"));
}

#[test]
fn request_builder_has_url_input() {
    let rendered = render! {
        TestContextProvider {
            RequestBuilder()
        }
    };
    let url = rendered.query_selector("input[name='url'], input[name='path']");
    assert!(url.is_some());
}

#[test]
fn request_builder_has_body_input() {
    let rendered = render! {
        TestContextProvider {
            RequestBuilder()
        }
    };
    let body = rendered.query_selector("textarea[name='body'], textarea, .body-editor");
    assert!(body.is_some());
}

#[test]
fn request_builder_has_send_button() {
    let rendered = render! {
        TestContextProvider {
            RequestBuilder()
        }
    };
    let send = rendered.query_selector("button[type='submit'], button.send-btn");
    assert!(send.is_some() || rendered.contains_text("Send"));
}

// ============================================================================
// RESPONSE VIEWER COMPONENT TESTS
// ============================================================================

#[test]
fn response_viewer_renders() {
    let rendered = render! {
        ResponseViewer()
    };
    assert!(rendered.query_selector(".component").is_some());
}

#[test]
fn response_viewer_shows_status() {
    let rendered = render_with_mock! {
        response: { status: 200, body: "{}" },
        ResponseViewer()
    };
    assert!(rendered.contains_text("200") || rendered.contains_text("OK"));
}

#[test]
fn response_viewer_shows_body() {
    let rendered = render_with_mock! {
        response: { status: 200, body: r#"{"items": []}"# },
        ResponseViewer()
    };
    assert!(rendered.contains_text("items"));
}

#[test]
fn response_viewer_formats_json() {
    let rendered = render_with_mock! {
        response: { status: 200, body: r#"{"key":"value"}"# },
        ResponseViewer()
    };
    // Should have code formatting
    let code = rendered.query_selector("pre, code, .json-viewer");
    assert!(code.is_some());
}

// ============================================================================
// INTEGRATION TESTS
// ============================================================================

#[test]
fn explorer_sends_request_on_submit() {
    let rendered = render! {
        TestContextProvider {
            CloudkitExplorerPage()
        }
    };

    // Fill in request
    rendered.fire_event("input[name='url']", "input", |e| e.value = "/s3/buckets");

    // Submit
    rendered.fire_event("form", "submit");

    // Should show loading or response
    assert!(rendered.is_ok());
}

// ============================================================================
// HELPER
// ============================================================================

#[component]
fn TestContextProvider(children: Children) -> Element {
    use crate::modules::context::AppContextProvider;
    rsx! { AppContextProvider { {children} } }
}
