//! Cloudkit E2E tests.
//!
//! End-to-end tests for cloudkit feature.
//! Generated by `rsc scaffold routes`

use rustscript::test::*;

#[e2e]
fn cloudkit_overview_page_loads() {
    navigate("/cloudkit");
    assert_url_contains("cloudkit");
    assert_no_errors();
}

#[e2e]
fn cloudkit_navigation_works() {
    navigate("/cloudkit");
    assert_element_exists(".cloudkit-page, .cloudkit-layout");
    assert_no_errors();
}
