//! Azure API clients.
//!
//! Generated by `rsc scaffold services`

use rustscript::prelude::*;
use super::api_base;

pub mod keyvault;
pub mod blobs;
pub mod queues;
pub mod functions;

pub use keyvault::KeyvaultClient;
pub use blobs::BlobsClient;
pub use queues::QueuesClient;
pub use functions::FunctionsClient;
