//! CloudKit Landing Page Tests
//!
//! Generated by `rsc scaffold routes`

use rsc::test::*;

// ============================================================================
// PAGE RENDER TESTS
// ============================================================================

#[test]
fn cloudkit_landing_renders_without_error() {
    let result = render! {
        TestContextProvider {
            CloudkitLandingPage()
        }
    };
    assert!(result.is_ok());
}

#[test]
fn cloudkit_landing_displays_title() {
    let rendered = render! {
        TestContextProvider {
            CloudkitLandingPage()
        }
    };
    assert!(rendered.contains_text("CloudKit"));
}

// ============================================================================
// CLOUDKIT OVERVIEW COMPONENT TESTS
// ============================================================================

#[test]
fn cloudkit_overview_renders() {
    let rendered = render! {
        TestContextProvider {
            CloudKitOverview()
        }
    };
    assert!(rendered.query_selector(".container").is_some());
}

#[test]
fn cloudkit_overview_shows_features() {
    let rendered = render! {
        TestContextProvider {
            CloudKitOverview()
        }
    };
    // Should show Resources, Operations, Explorer
    assert!(rendered.contains_text("Resources") ||
            rendered.contains_text("Operations") ||
            rendered.contains_text("Explorer"));
}

// ============================================================================
// RECENT OPERATIONS COMPONENT TESTS
// ============================================================================

#[test]
fn recent_operations_renders() {
    let rendered = render! {
        TestContextProvider {
            RecentOperations()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn recent_operations_shows_loading() {
    let rendered = render! {
        TestContextProvider {
            RecentOperations()
        }
    };
    assert!(rendered.contains_text("Loading") || rendered.query_selector(".loading").is_some());
}

#[test]
fn recent_operations_displays_items() {
    let rendered = render_with_mock! {
        data: [
            { id: "1", operation: "CreateBucket", status: "success", timestamp: "2024-01-15" },
            { id: "2", operation: "PutItem", status: "success", timestamp: "2024-01-15" },
        ],
        RecentOperations()
    };
    let items = rendered.query_selector_all("li, .operation-item");
    assert!(items.len() >= 2);
}

// ============================================================================
// NAVIGATION TESTS
// ============================================================================

#[test]
fn cloudkit_landing_has_resources_link() {
    let rendered = render! {
        TestContextProvider {
            CloudkitLandingPage()
        }
    };
    let link = rendered.query_selector("a[href='/cloudkit/resources']");
    assert!(link.is_some());
}

#[test]
fn cloudkit_landing_has_operations_link() {
    let rendered = render! {
        TestContextProvider {
            CloudkitLandingPage()
        }
    };
    let link = rendered.query_selector("a[href='/cloudkit/operations']");
    assert!(link.is_some());
}

#[test]
fn cloudkit_landing_has_explorer_link() {
    let rendered = render! {
        TestContextProvider {
            CloudkitLandingPage()
        }
    };
    let link = rendered.query_selector("a[href='/cloudkit/explorer']");
    assert!(link.is_some());
}

// ============================================================================
// HELPER
// ============================================================================

#[component]
fn TestContextProvider(children: Children) -> Element {
    use @modules::context::AppContextProvider;
    rsx! { AppContextProvider { {children} } }
}
