//! Cloudkit integration tests.
//!
//! Integration tests for cloudkit feature.
//! Generated by `rsc scaffold routes`

use rustscript::test::*;
use rustscript::render::*;

#[integration]
fn cloudkit_module_initializes() {
    // Module should initialize without errors
    let result = init_module::<CloudkitModule>();
    assert!(result.is_ok());
}

#[integration]
fn cloudkit_routes_registered() {
    let router = Router::from_config();
    let routes = router.routes_for_prefix("/cloudkit");
    assert!(!routes.is_empty(), "cloudkit routes should be registered");
}

#[integration]
fn cloudkit_landing_renders_with_context() {
    let ctx = CloudkitContext::default();
    let result = render_with_context::<CloudkitLanding>(ctx);
    assert!(result.is_ok());
}

