//! Mock clients for testing.
//!
//! Generated by `rsc scaffold services`

pub mod dynamodb_mock;
pub use dynamodb_mock::DynamodbClientMock;
pub mod lambda_mock;
pub use lambda_mock::LambdaClientMock;
pub mod sns_mock;
pub use sns_mock::SnsClientMock;
pub mod ec2_mock;
pub use ec2_mock::Ec2ClientMock;
pub mod sqs_mock;
pub use sqs_mock::SqsClientMock;
pub mod s3_mock;
pub use s3_mock::S3ClientMock;
