//! Route navigation tests.
//!
//! Generated by `rsc scaffold routes`

use rustscript::test::*;
use rustscript::router::TestRouter;

#[test]
fn navigates_to_dashboard() {
    let router = TestRouter::new();
    router.navigate("/");

    assert_eq!(router.current_path(), "/");
    assert!(router.current_page().is_some());
}

#[test]
fn navigates_to_cloudemu_overview() {
    let router = TestRouter::new();
    router.navigate("/cloudemu");

    assert_eq!(router.current_path(), "/cloudemu");
    assert!(router.current_page().is_some());
}

#[test]
fn navigates_to_cloudkit_overview() {
    let router = TestRouter::new();
    router.navigate("/cloudkit");

    assert_eq!(router.current_path(), "/cloudkit");
    assert!(router.current_page().is_some());
}

#[test]
fn navigates_to_iac_overview() {
    let router = TestRouter::new();
    router.navigate("/iac");

    assert_eq!(router.current_path(), "/iac");
    assert!(router.current_page().is_some());
}

#[test]
fn navigates_to_workflow_runner() {
    let router = TestRouter::new();
    router.navigate("/workflow/:workflow_id");

    assert_eq!(router.current_path(), "/workflow/:workflow_id");
    assert!(router.current_page().is_some());
}

#[test]
fn navigates_to_settings_index() {
    let router = TestRouter::new();
    router.navigate("/settings");

    assert_eq!(router.current_path(), "/settings");
    assert!(router.current_page().is_some());
}

#[test]
fn navigates_to_not_found() {
    let router = TestRouter::new();
    router.navigate("*");

    assert_eq!(router.current_path(), "*");
    assert!(router.current_page().is_some());
}

