//! Cloudemu integration tests.
//!
//! Integration tests for cloudemu feature.
//! Generated by `rsc scaffold routes`

use rustscript::test::*;
use rustscript::render::*;

#[integration]
fn cloudemu_module_initializes() {
    // Module should initialize without errors
    let result = init_module::<CloudemuModule>();
    assert!(result.is_ok());
}

#[integration]
fn cloudemu_routes_registered() {
    let router = Router::from_config();
    let routes = router.routes_for_prefix("/cloudemu");
    assert!(!routes.is_empty(), "cloudemu routes should be registered");
}

#[integration]
fn cloudemu_landing_renders_with_context() {
    let ctx = CloudemuContext::default();
    let result = render_with_context::<CloudemuLanding>(ctx);
    assert!(result.is_ok());
}

