//! CloudemuOverview page component.
//!
//! Route: /cloudemu
//! Generated by `rsc scaffold routes`

use rustscript::prelude::*;

#[component]
pub fn CloudemuOverview() -> Element {
    render! {
        <div class="cloudemu-overview-page">
            <h1>"CloudEmu"</h1>
            // TODO: Implement page content
        </div>
    }
}
