//! CloudkitOverview page component.
//!
//! Route: /cloudkit
//! Generated by `rsc scaffold routes`

use rustscript::prelude::*;

#[component]
pub fn CloudkitOverview() -> Element {
    render! {
        <div class="cloudkit-overview-page">
            <h1>"CloudKit"</h1>
            // TODO: Implement page content
        </div>
    }
}
