//! CloudkitOverview page component.
//!
//! Route: /cloudkit
//! Generated by `rsc scaffold routes`

use rsc::prelude::*;
use crate::features::cloudkit::CloudkitLayout;

#[component]
pub fn CloudkitOverview() -> Element {
    rsx! {
        CloudkitLayout {
            div(class: "cloudkit-overview-page") {
                h1 { "CloudKit" }
                p { "Cloud Infrastructure Toolkit" }
            }
        }
    }
}
