//! Dashboard page component.
//!
//! Route: /
//! Generated by `rsc scaffold routes`

use rustscript::prelude::*;

#[component]
pub fn Dashboard() -> Element {
    rsx! {
        <div class="dashboard-page">
            <h1>"Dashboard"</h1>
        </div>
    }
}
