//! IacOverview page component.
//!
//! Route: /iac
//! Generated by `rsc scaffold routes`

use rustscript::prelude::*;

#[component]
pub fn IacOverview() -> Element {
    render! {
        <div class="iac-overview-page">
            <h1>"Infrastructure"</h1>
            // TODO: Implement page content
        </div>
    }
}
