//! IacOverview page component.
//!
//! Route: /iac
//! Generated by `rsc scaffold routes`

use rustscript::prelude::*;

#[component]
pub fn IacOverview() -> Element {
    rsx! {
        <div class="iac-overview-page">
            <h1>"Infrastructure"</h1>
        </div>
    }
}
