//! SettingsIndex page component.
//!
//! Route: /settings
//! Generated by `rsc scaffold routes`

use rustscript::prelude::*;

#[component]
pub fn SettingsIndex() -> Element {
    render! {
        <div class="settings-index-page">
            <h1>"Settings"</h1>
            // TODO: Implement page content
        </div>
    }
}
