//! SettingsIndex page component.
//!
//! Route: /settings
//! Generated by `rsc scaffold routes`

use rustscript::prelude::*;

#[component]
pub fn SettingsIndex() -> Element {
    rsx! {
        <div class="settings-index-page">
            <h1>"Settings"</h1>
        </div>
    }
}
