//! WorkflowRunner page component.
//!
//! Route: /workflow/:workflow_id
//! Generated by `rsc scaffold routes`

use rustscript::prelude::*;

#[component]
pub fn WorkflowRunner() -> Element {
    render! {
        <div class="workflow-runner-page">
            <h1>"Workflow"</h1>
            // TODO: Implement page content
        </div>
    }
}
