//! Cloudemu E2E tests.
//!
//! End-to-end tests for cloudemu feature.
//! Generated by `rsc scaffold routes`

use rustscript::test::*;

#[e2e]
fn cloudemu_overview_page_loads() {
    navigate("/cloudemu");
    assert_url_contains("cloudemu");
    assert_no_errors();
}

#[e2e]
fn cloudemu_navigation_works() {
    navigate("/cloudemu");
    assert_element_exists(".cloudemu-page, .cloudemu-layout");
    assert_no_errors();
}
