//! IAC Deploy Page Tests
//!
//! Generated by `rsc scaffold routes`

use rsc::test::*;

// ============================================================================
// PAGE RENDER TESTS
// ============================================================================

#[test]
fn iac_deploy_renders_without_error() {
    let result = render! {
        TestContextProvider {
            IacDeployPage()
        }
    };
    assert!(result.is_ok());
}

#[test]
fn iac_deploy_displays_title() {
    let rendered = render! {
        TestContextProvider {
            IacDeployPage()
        }
    };
    assert!(rendered.contains_text("Deploy"));
}

// ============================================================================
// DEPLOY FORM COMPONENT TESTS
// ============================================================================

#[test]
fn deploy_form_renders() {
    let rendered = render! {
        TestContextProvider {
            DeployForm()
        }
    };
    assert!(rendered.query_selector("form, .form-container").is_some());
}

#[test]
fn deploy_form_has_module_selector() {
    let rendered = render! {
        TestContextProvider {
            DeployForm()
        }
    };
    let module = rendered.query_selector("select[name='module'], input[name='module']");
    assert!(module.is_some() || rendered.contains_text("Module"));
}

#[test]
fn deploy_form_has_environment_selector() {
    let rendered = render! {
        TestContextProvider {
            DeployForm()
        }
    };
    let env = rendered.query_selector("select[name='environment'], input[name='environment']");
    assert!(env.is_some() || rendered.contains_text("Environment"));
}

#[test]
fn deploy_form_has_submit_button() {
    let rendered = render! {
        TestContextProvider {
            DeployForm()
        }
    };
    let submit = rendered.query_selector("button[type='submit']");
    assert!(submit.is_some() || rendered.contains_text("Deploy") || rendered.contains_text("Plan"));
}

// ============================================================================
// DEPLOY PREVIEW COMPONENT TESTS
// ============================================================================

#[test]
fn deploy_preview_renders() {
    let rendered = render! {
        DeployPreview()
    };
    assert!(rendered.query_selector(".component").is_some());
}

#[test]
fn deploy_preview_shows_changes() {
    let rendered = render_with_mock! {
        plan: {
            add: 3,
            change: 2,
            destroy: 1,
            resources: [
                { action: "add", type: "aws_s3_bucket", name: "main" },
            ]
        },
        DeployPreview()
    };
    assert!(rendered.contains_text("add") ||
            rendered.contains_text("change") ||
            rendered.contains_text("+"));
}

// ============================================================================
// DEPLOY CONFIRM MODAL COMPONENT TESTS
// ============================================================================

#[test]
fn deploy_confirm_modal_renders() {
    let rendered = render! {
        DeployConfirmModal()
    };
    assert!(rendered.is_ok());
}

#[test]
fn deploy_confirm_modal_has_confirm_button() {
    let rendered = render_with_state! {
        is_open: true,
        DeployConfirmModal()
    };
    assert!(rendered.contains_text("Confirm") || rendered.contains_text("Deploy"));
}

#[test]
fn deploy_confirm_modal_has_cancel_button() {
    let rendered = render_with_state! {
        is_open: true,
        DeployConfirmModal()
    };
    assert!(rendered.contains_text("Cancel"));
}

#[test]
fn deploy_confirm_modal_shows_warning_for_production() {
    let rendered = render_with_context! {
        environment: "prod",
        is_open: true,
        DeployConfirmModal()
    };
    assert!(rendered.contains_text("production") ||
            rendered.contains_text("warning") ||
            rendered.query_selector(".warning").is_some());
}

// ============================================================================
// ENVIRONMENT SAFETY TESTS
// ============================================================================

#[test]
fn deploy_form_warns_for_production() {
    let rendered = render_with_context! {
        environment: "prod",
        DeployForm()
    };
    assert!(rendered.contains_text("production") ||
            rendered.query_selector(".warning, .alert").is_some());
}

#[test]
fn deploy_requires_confirmation_for_production() {
    let rendered = render_with_context! {
        environment: "prod",
        IacDeployPage()
    };
    // Production should require modal confirmation
    assert!(rendered.is_ok());
}

// ============================================================================
// HELPER
// ============================================================================

#[component]
fn TestContextProvider(children: Children) -> Element {
    use @modules::context::AppContextProvider;
    rsx! { AppContextProvider { {children} } }
}
