//! Aws API clients.
//!
//! Generated by `rsc scaffold services`

use rustscript::prelude::*;
use super::api_base;

pub mod dynamodb;
pub mod lambda;
pub mod sns;
pub mod ec2;
pub mod sqs;
pub mod s3;

pub use dynamodb::DynamodbClient;
pub use lambda::LambdaClient;
pub use sns::SnsClient;
pub use ec2::Ec2Client;
pub use sqs::SqsClient;
pub use s3::S3Client;
