//! CloudEmu Logs Page Tests
//!
//! Generated by `rsc scaffold routes`

use rsc::test::*;

// ============================================================================
// PAGE RENDER TESTS
// ============================================================================

#[test]
fn cloudemu_logs_renders_without_error() {
    let result = render! {
        TestContextProvider {
            CloudemuLogsPage()
        }
    };
    assert!(result.is_ok());
}

#[test]
fn cloudemu_logs_displays_title() {
    let rendered = render! {
        TestContextProvider {
            CloudemuLogsPage()
        }
    };
    assert!(rendered.contains_text("Logs") || rendered.contains_text("Request"));
}

// ============================================================================
// LOG VIEWER COMPONENT TESTS
// ============================================================================

#[test]
fn log_viewer_renders() {
    let rendered = render! {
        TestContextProvider {
            LogViewer()
        }
    };
    assert!(rendered.query_selector(".container").is_some());
}

#[test]
fn log_viewer_shows_loading() {
    let rendered = render! {
        TestContextProvider {
            LogViewer()
        }
    };
    // Initially loading or showing logs
    assert!(rendered.is_ok());
}

#[test]
fn log_viewer_displays_log_entries() {
    let rendered = render_with_mock! {
        logs: [
            { timestamp: "2024-01-15T10:00:00Z", method: "GET", path: "/s3/bucket", status: 200 },
            { timestamp: "2024-01-15T10:01:00Z", method: "PUT", path: "/s3/bucket/object", status: 201 },
        ],
        LogViewer()
    };
    let entries = rendered.query_selector_all(".log-entry, tr, li");
    assert!(entries.len() >= 2);
}

#[test]
fn log_viewer_shows_method() {
    let rendered = render_with_mock! {
        logs: [{ method: "GET", path: "/test", status: 200 }],
        LogViewer()
    };
    assert!(rendered.contains_text("GET"));
}

#[test]
fn log_viewer_shows_status_code() {
    let rendered = render_with_mock! {
        logs: [{ method: "GET", path: "/test", status: 404 }],
        LogViewer()
    };
    assert!(rendered.contains_text("404"));
}

// ============================================================================
// LOG FILTERS COMPONENT TESTS
// ============================================================================

#[test]
fn log_filters_renders() {
    let rendered = render! {
        TestContextProvider {
            LogFilters()
        }
    };
    assert!(rendered.query_selector("form, .form-container").is_some());
}

#[test]
fn log_filters_has_method_filter() {
    let rendered = render! {
        TestContextProvider {
            LogFilters()
        }
    };
    let method_filter = rendered.query_selector("select[name='method'], input[name='method']");
    assert!(method_filter.is_some() || rendered.contains_text("Method"));
}

#[test]
fn log_filters_has_status_filter() {
    let rendered = render! {
        TestContextProvider {
            LogFilters()
        }
    };
    let status_filter = rendered.query_selector("select[name='status'], input[name='status']");
    assert!(status_filter.is_some() || rendered.contains_text("Status"));
}

#[test]
fn log_filters_has_search() {
    let rendered = render! {
        TestContextProvider {
            LogFilters()
        }
    };
    let search = rendered.query_selector("input[type='search'], input[name='search']");
    assert!(search.is_some());
}

// ============================================================================
// LOG DETAIL PANEL COMPONENT TESTS
// ============================================================================

#[test]
fn log_detail_panel_renders() {
    let rendered = render! {
        LogDetailPanel()
    };
    assert!(rendered.query_selector(".component").is_some());
}

#[test]
fn log_detail_panel_shows_request_body() {
    let rendered = render_with_mock! {
        log: {
            method: "POST",
            path: "/s3/bucket",
            request_body: r#"{"key": "value"}"#
        },
        LogDetailPanel()
    };
    assert!(rendered.contains_text("request") || rendered.contains_text("body"));
}

#[test]
fn log_detail_panel_shows_response_body() {
    let rendered = render_with_mock! {
        log: {
            method: "GET",
            path: "/s3/bucket",
            response_body: r#"{"items": []}"#
        },
        LogDetailPanel()
    };
    assert!(rendered.contains_text("response") || rendered.contains_text("items"));
}

// ============================================================================
// REAL-TIME UPDATES TESTS
// ============================================================================

#[test]
fn logs_page_supports_auto_refresh() {
    let rendered = render! {
        TestContextProvider {
            CloudemuLogsPage()
        }
    };
    let auto_refresh = rendered.query_selector("input[name='auto_refresh'], button.refresh");
    assert!(auto_refresh.is_some() || rendered.contains_text("Auto") || rendered.contains_text("Refresh"));
}

// ============================================================================
// CONTEXT FILTERING TESTS
// ============================================================================

#[test]
fn logs_filter_by_current_provider() {
    let rendered = render_with_context! {
        provider: "aws",
        CloudemuLogsPage()
    };
    // Should only show AWS-related logs
    assert!(rendered.is_ok());
}

// ============================================================================
// HELPER
// ============================================================================

#[component]
fn TestContextProvider(children: Children) -> Element {
    use @modules::context::AppContextProvider;
    rsx! { AppContextProvider { {children} } }
}
