//! Settings E2E tests.
//!
//! End-to-end tests for settings feature.
//! Generated by `rsc scaffold routes`

use rustscript::test::*;

#[e2e]
fn settings_index_page_loads() {
    navigate("/settings");
    assert_url_contains("settings");
    assert_no_errors();
}

#[e2e]
fn settings_navigation_works() {
    navigate("/settings");
    assert_element_exists(".settings-page, .settings-layout");
    assert_no_errors();
}
