//! Mock clients for testing.
//!
//! Generated by `rsc scaffold services`

pub mod keyvault_mock;
pub use keyvault_mock::KeyvaultClientMock;
pub mod blobs_mock;
pub use blobs_mock::BlobsClientMock;
pub mod queues_mock;
pub use queues_mock::QueuesClientMock;
pub mod functions_mock;
pub use functions_mock::FunctionsClientMock;
