//! Tests for Aws Lambda client.
//!
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use crate::api::aws::lambda::*;
use crate::api::mocks::aws::LambdaClientMock;

#[test]
fn lambda_client_can_be_created() {
    let client = LambdaClient::new();
    // Client should be created successfully
}

#[test]
fn lambda_client_with_custom_base_url() {
    let client = LambdaClient::with_base_url("http://custom:8080");
    // Client should accept custom base URL
}

#[tokio::test]
async fn lambda_create_function_with_mock() {
    let mock = LambdaClientMock::new()
        .with_response("CreateFunction", CreateFunctionResponse::default());

    let request = CreateFunctionRequest::default();
    let result = mock.create_function(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("CreateFunction"));
}

#[tokio::test]
async fn lambda_delete_function_with_mock() {
    let mock = LambdaClientMock::new()
        .with_response("DeleteFunction", DeleteFunctionResponse::default());

    let request = DeleteFunctionRequest::default();
    let result = mock.delete_function(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteFunction"));
}

#[tokio::test]
async fn lambda_list_functions_with_mock() {
    let mock = LambdaClientMock::new()
        .with_response("ListFunctions", ListFunctionsResponse::default());

    let request = ListFunctionsRequest::default();
    let result = mock.list_functions(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("ListFunctions"));
}

#[tokio::test]
async fn lambda_invoke_with_mock() {
    let mock = LambdaClientMock::new()
        .with_response("Invoke", InvokeResponse::default());

    let request = InvokeRequest::default();
    let result = mock.invoke(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("Invoke"));
}

#[tokio::test]
async fn lambda_update_function_code_with_mock() {
    let mock = LambdaClientMock::new()
        .with_response("UpdateFunctionCode", UpdateFunctionCodeResponse::default());

    let request = UpdateFunctionCodeRequest::default();
    let result = mock.update_function_code(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("UpdateFunctionCode"));
}

#[tokio::test]
async fn lambda_update_function_configuration_with_mock() {
    let mock = LambdaClientMock::new()
        .with_response("UpdateFunctionConfiguration", UpdateFunctionConfigurationResponse::default());

    let request = UpdateFunctionConfigurationRequest::default();
    let result = mock.update_function_configuration(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("UpdateFunctionConfiguration"));
}

