//! Tests for Aws EC2 client.
//!
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use crate::api::aws::ec2::*;
use crate::api::mocks::aws::Ec2ClientMock;

#[test]
fn ec2_client_can_be_created() {
    let client = Ec2Client::new();
    // Client should be created successfully
}

#[test]
fn ec2_client_with_custom_base_url() {
    let client = Ec2Client::with_base_url("http://custom:8080");
    // Client should accept custom base URL
}

#[tokio::test]
async fn ec2_run_instances_with_mock() {
    let mock = Ec2ClientMock::new()
        .with_response("RunInstances", RunInstancesResponse::default());

    let request = RunInstancesRequest::default();
    let result = mock.run_instances(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("RunInstances"));
}

#[tokio::test]
async fn ec2_terminate_instances_with_mock() {
    let mock = Ec2ClientMock::new()
        .with_response("TerminateInstances", TerminateInstancesResponse::default());

    let request = TerminateInstancesRequest::default();
    let result = mock.terminate_instances(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("TerminateInstances"));
}

#[tokio::test]
async fn ec2_describe_instances_with_mock() {
    let mock = Ec2ClientMock::new()
        .with_response("DescribeInstances", DescribeInstancesResponse::default());

    let request = DescribeInstancesRequest::default();
    let result = mock.describe_instances(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DescribeInstances"));
}

#[tokio::test]
async fn ec2_start_instances_with_mock() {
    let mock = Ec2ClientMock::new()
        .with_response("StartInstances", StartInstancesResponse::default());

    let request = StartInstancesRequest::default();
    let result = mock.start_instances(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("StartInstances"));
}

#[tokio::test]
async fn ec2_stop_instances_with_mock() {
    let mock = Ec2ClientMock::new()
        .with_response("StopInstances", StopInstancesResponse::default());

    let request = StopInstancesRequest::default();
    let result = mock.stop_instances(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("StopInstances"));
}

