//! Tests for Aws DynamoDB client.
//!
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use crate::api::aws::dynamodb::*;
use crate::api::mocks::aws::DynamodbClientMock;

#[test]
fn dynamodb_client_can_be_created() {
    let client = DynamodbClient::new();
    // Client should be created successfully
}

#[test]
fn dynamodb_client_with_custom_base_url() {
    let client = DynamodbClient::with_base_url("http://custom:8080");
    // Client should accept custom base URL
}

#[tokio::test]
async fn dynamodb_create_table_with_mock() {
    let mock = DynamodbClientMock::new()
        .with_response("CreateTable", CreateTableResponse::default());

    let request = CreateTableRequest::default();
    let result = mock.create_table(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("CreateTable"));
}

#[tokio::test]
async fn dynamodb_delete_table_with_mock() {
    let mock = DynamodbClientMock::new()
        .with_response("DeleteTable", DeleteTableResponse::default());

    let request = DeleteTableRequest::default();
    let result = mock.delete_table(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteTable"));
}

#[tokio::test]
async fn dynamodb_list_tables_with_mock() {
    let mock = DynamodbClientMock::new()
        .with_response("ListTables", ListTablesResponse::default());

    let request = ListTablesRequest::default();
    let result = mock.list_tables(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("ListTables"));
}

#[tokio::test]
async fn dynamodb_put_item_with_mock() {
    let mock = DynamodbClientMock::new()
        .with_response("PutItem", PutItemResponse::default());

    let request = PutItemRequest::default();
    let result = mock.put_item(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("PutItem"));
}

#[tokio::test]
async fn dynamodb_get_item_with_mock() {
    let mock = DynamodbClientMock::new()
        .with_response("GetItem", GetItemResponse::default());

    let request = GetItemRequest::default();
    let result = mock.get_item(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("GetItem"));
}

#[tokio::test]
async fn dynamodb_delete_item_with_mock() {
    let mock = DynamodbClientMock::new()
        .with_response("DeleteItem", DeleteItemResponse::default());

    let request = DeleteItemRequest::default();
    let result = mock.delete_item(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteItem"));
}

#[tokio::test]
async fn dynamodb_query_with_mock() {
    let mock = DynamodbClientMock::new()
        .with_response("Query", QueryResponse::default());

    let request = QueryRequest::default();
    let result = mock.query(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("Query"));
}

#[tokio::test]
async fn dynamodb_scan_with_mock() {
    let mock = DynamodbClientMock::new()
        .with_response("Scan", ScanResponse::default());

    let request = ScanRequest::default();
    let result = mock.scan(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("Scan"));
}

