//! Tests for Aws SNS client.
//!
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use crate::api::aws::sns::*;
use crate::api::mocks::aws::SnsClientMock;

#[test]
fn sns_client_can_be_created() {
    let client = SnsClient::new();
    // Client should be created successfully
}

#[test]
fn sns_client_with_custom_base_url() {
    let client = SnsClient::with_base_url("http://custom:8080");
    // Client should accept custom base URL
}

#[tokio::test]
async fn sns_create_topic_with_mock() {
    let mock = SnsClientMock::new()
        .with_response("CreateTopic", CreateTopicResponse::default());

    let request = CreateTopicRequest::default();
    let result = mock.create_topic(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("CreateTopic"));
}

#[tokio::test]
async fn sns_delete_topic_with_mock() {
    let mock = SnsClientMock::new()
        .with_response("DeleteTopic", DeleteTopicResponse::default());

    let request = DeleteTopicRequest::default();
    let result = mock.delete_topic(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteTopic"));
}

#[tokio::test]
async fn sns_list_topics_with_mock() {
    let mock = SnsClientMock::new()
        .with_response("ListTopics", ListTopicsResponse::default());

    let request = ListTopicsRequest::default();
    let result = mock.list_topics(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("ListTopics"));
}

#[tokio::test]
async fn sns_publish_with_mock() {
    let mock = SnsClientMock::new()
        .with_response("Publish", PublishResponse::default());

    let request = PublishRequest::default();
    let result = mock.publish(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("Publish"));
}

#[tokio::test]
async fn sns_subscribe_with_mock() {
    let mock = SnsClientMock::new()
        .with_response("Subscribe", SubscribeResponse::default());

    let request = SubscribeRequest::default();
    let result = mock.subscribe(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("Subscribe"));
}

#[tokio::test]
async fn sns_unsubscribe_with_mock() {
    let mock = SnsClientMock::new()
        .with_response("Unsubscribe", UnsubscribeResponse::default());

    let request = UnsubscribeRequest::default();
    let result = mock.unsubscribe(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("Unsubscribe"));
}

