//! Tests for Aws S3 client.
//!
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use crate::api::aws::s3::*;
use crate::api::mocks::aws::S3ClientMock;

#[test]
fn s3_client_can_be_created() {
    let client = S3Client::new();
    // Client should be created successfully
}

#[test]
fn s3_client_with_custom_base_url() {
    let client = S3Client::with_base_url("http://custom:8080");
    // Client should accept custom base URL
}

#[tokio::test]
async fn s3_create_bucket_with_mock() {
    let mock = S3ClientMock::new()
        .with_response("CreateBucket", CreateBucketResponse::default());

    let request = CreateBucketRequest::default();
    let result = mock.create_bucket(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("CreateBucket"));
}

#[tokio::test]
async fn s3_delete_bucket_with_mock() {
    let mock = S3ClientMock::new()
        .with_response("DeleteBucket", DeleteBucketResponse::default());

    let request = DeleteBucketRequest::default();
    let result = mock.delete_bucket(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteBucket"));
}

#[tokio::test]
async fn s3_list_buckets_with_mock() {
    let mock = S3ClientMock::new()
        .with_response("ListBuckets", ListBucketsResponse::default());

    let request = ListBucketsRequest::default();
    let result = mock.list_buckets(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("ListBuckets"));
}

#[tokio::test]
async fn s3_put_object_with_mock() {
    let mock = S3ClientMock::new()
        .with_response("PutObject", PutObjectResponse::default());

    let request = PutObjectRequest::default();
    let result = mock.put_object(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("PutObject"));
}

#[tokio::test]
async fn s3_get_object_with_mock() {
    let mock = S3ClientMock::new()
        .with_response("GetObject", GetObjectResponse::default());

    let request = GetObjectRequest::default();
    let result = mock.get_object(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("GetObject"));
}

#[tokio::test]
async fn s3_delete_object_with_mock() {
    let mock = S3ClientMock::new()
        .with_response("DeleteObject", DeleteObjectResponse::default());

    let request = DeleteObjectRequest::default();
    let result = mock.delete_object(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteObject"));
}

#[tokio::test]
async fn s3_list_objects_with_mock() {
    let mock = S3ClientMock::new()
        .with_response("ListObjects", ListObjectsResponse::default());

    let request = ListObjectsRequest::default();
    let result = mock.list_objects(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("ListObjects"));
}

