//! Tests for Azure Functions client.
//!
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use crate::api::azure::functions::*;
use crate::api::mocks::azure::FunctionsClientMock;

#[test]
fn functions_client_can_be_created() {
    let client = FunctionsClient::new();
    // Client should be created successfully
}

#[test]
fn functions_client_with_custom_base_url() {
    let client = FunctionsClient::with_base_url("http://custom:8080");
    // Client should accept custom base URL
}

#[tokio::test]
async fn functions_create_function_with_mock() {
    let mock = FunctionsClientMock::new()
        .with_response("CreateFunction", CreateFunctionResponse::default());

    let request = CreateFunctionRequest::default();
    let result = mock.create_function(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("CreateFunction"));
}

#[tokio::test]
async fn functions_delete_function_with_mock() {
    let mock = FunctionsClientMock::new()
        .with_response("DeleteFunction", DeleteFunctionResponse::default());

    let request = DeleteFunctionRequest::default();
    let result = mock.delete_function(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteFunction"));
}

#[tokio::test]
async fn functions_list_functions_with_mock() {
    let mock = FunctionsClientMock::new()
        .with_response("ListFunctions", ListFunctionsResponse::default());

    let request = ListFunctionsRequest::default();
    let result = mock.list_functions(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("ListFunctions"));
}

#[tokio::test]
async fn functions_invoke_function_with_mock() {
    let mock = FunctionsClientMock::new()
        .with_response("InvokeFunction", InvokeFunctionResponse::default());

    let request = InvokeFunctionRequest::default();
    let result = mock.invoke_function(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("InvokeFunction"));
}

