//! Tests for Azure Key Vault client.
//!
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use crate::api::azure::keyvault::*;
use crate::api::mocks::azure::KeyvaultClientMock;

#[test]
fn keyvault_client_can_be_created() {
    let client = KeyvaultClient::new();
    // Client should be created successfully
}

#[test]
fn keyvault_client_with_custom_base_url() {
    let client = KeyvaultClient::with_base_url("http://custom:8080");
    // Client should accept custom base URL
}

#[tokio::test]
async fn keyvault_create_secret_with_mock() {
    let mock = KeyvaultClientMock::new()
        .with_response("CreateSecret", CreateSecretResponse::default());

    let request = CreateSecretRequest::default();
    let result = mock.create_secret(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("CreateSecret"));
}

#[tokio::test]
async fn keyvault_get_secret_with_mock() {
    let mock = KeyvaultClientMock::new()
        .with_response("GetSecret", GetSecretResponse::default());

    let request = GetSecretRequest::default();
    let result = mock.get_secret(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("GetSecret"));
}

#[tokio::test]
async fn keyvault_delete_secret_with_mock() {
    let mock = KeyvaultClientMock::new()
        .with_response("DeleteSecret", DeleteSecretResponse::default());

    let request = DeleteSecretRequest::default();
    let result = mock.delete_secret(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteSecret"));
}

#[tokio::test]
async fn keyvault_list_secrets_with_mock() {
    let mock = KeyvaultClientMock::new()
        .with_response("ListSecrets", ListSecretsResponse::default());

    let request = ListSecretsRequest::default();
    let result = mock.list_secrets(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("ListSecrets"));
}

