//! Tests for Azure Blob Storage client.
//!
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use crate::api::azure::blobs::*;
use crate::api::mocks::azure::BlobsClientMock;

#[test]
fn blobs_client_can_be_created() {
    let client = BlobsClient::new();
    // Client should be created successfully
}

#[test]
fn blobs_client_with_custom_base_url() {
    let client = BlobsClient::with_base_url("http://custom:8080");
    // Client should accept custom base URL
}

#[tokio::test]
async fn blobs_create_container_with_mock() {
    let mock = BlobsClientMock::new()
        .with_response("CreateContainer", CreateContainerResponse::default());

    let request = CreateContainerRequest::default();
    let result = mock.create_container(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("CreateContainer"));
}

#[tokio::test]
async fn blobs_delete_container_with_mock() {
    let mock = BlobsClientMock::new()
        .with_response("DeleteContainer", DeleteContainerResponse::default());

    let request = DeleteContainerRequest::default();
    let result = mock.delete_container(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteContainer"));
}

#[tokio::test]
async fn blobs_list_containers_with_mock() {
    let mock = BlobsClientMock::new()
        .with_response("ListContainers", ListContainersResponse::default());

    let request = ListContainersRequest::default();
    let result = mock.list_containers(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("ListContainers"));
}

#[tokio::test]
async fn blobs_upload_blob_with_mock() {
    let mock = BlobsClientMock::new()
        .with_response("UploadBlob", UploadBlobResponse::default());

    let request = UploadBlobRequest::default();
    let result = mock.upload_blob(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("UploadBlob"));
}

#[tokio::test]
async fn blobs_download_blob_with_mock() {
    let mock = BlobsClientMock::new()
        .with_response("DownloadBlob", DownloadBlobResponse::default());

    let request = DownloadBlobRequest::default();
    let result = mock.download_blob(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DownloadBlob"));
}

#[tokio::test]
async fn blobs_delete_blob_with_mock() {
    let mock = BlobsClientMock::new()
        .with_response("DeleteBlob", DeleteBlobResponse::default());

    let request = DeleteBlobRequest::default();
    let result = mock.delete_blob(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteBlob"));
}

#[tokio::test]
async fn blobs_list_blobs_with_mock() {
    let mock = BlobsClientMock::new()
        .with_response("ListBlobs", ListBlobsResponse::default());

    let request = ListBlobsRequest::default();
    let result = mock.list_blobs(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("ListBlobs"));
}

