//! Tests for Azure Queues client.
//!
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use crate::api::azure::queues::*;
use crate::api::mocks::azure::QueuesClientMock;

#[test]
fn queues_client_can_be_created() {
    let client = QueuesClient::new();
    // Client should be created successfully
}

#[test]
fn queues_client_with_custom_base_url() {
    let client = QueuesClient::with_base_url("http://custom:8080");
    // Client should accept custom base URL
}

#[tokio::test]
async fn queues_create_queue_with_mock() {
    let mock = QueuesClientMock::new()
        .with_response("CreateQueue", CreateQueueResponse::default());

    let request = CreateQueueRequest::default();
    let result = mock.create_queue(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("CreateQueue"));
}

#[tokio::test]
async fn queues_delete_queue_with_mock() {
    let mock = QueuesClientMock::new()
        .with_response("DeleteQueue", DeleteQueueResponse::default());

    let request = DeleteQueueRequest::default();
    let result = mock.delete_queue(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteQueue"));
}

#[tokio::test]
async fn queues_list_queues_with_mock() {
    let mock = QueuesClientMock::new()
        .with_response("ListQueues", ListQueuesResponse::default());

    let request = ListQueuesRequest::default();
    let result = mock.list_queues(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("ListQueues"));
}

#[tokio::test]
async fn queues_send_message_with_mock() {
    let mock = QueuesClientMock::new()
        .with_response("SendMessage", SendMessageResponse::default());

    let request = SendMessageRequest::default();
    let result = mock.send_message(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("SendMessage"));
}

#[tokio::test]
async fn queues_receive_message_with_mock() {
    let mock = QueuesClientMock::new()
        .with_response("ReceiveMessage", ReceiveMessageResponse::default());

    let request = ReceiveMessageRequest::default();
    let result = mock.receive_message(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("ReceiveMessage"));
}

