//! Tests for Gcp Pub/Sub client.
//!
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use crate::api::gcp::pubsub::*;
use crate::api::mocks::gcp::PubsubClientMock;

#[test]
fn pubsub_client_can_be_created() {
    let client = PubsubClient::new();
    // Client should be created successfully
}

#[test]
fn pubsub_client_with_custom_base_url() {
    let client = PubsubClient::with_base_url("http://custom:8080");
    // Client should accept custom base URL
}

#[tokio::test]
async fn pubsub_create_topic_with_mock() {
    let mock = PubsubClientMock::new()
        .with_response("CreateTopic", CreateTopicResponse::default());

    let request = CreateTopicRequest::default();
    let result = mock.create_topic(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("CreateTopic"));
}

#[tokio::test]
async fn pubsub_delete_topic_with_mock() {
    let mock = PubsubClientMock::new()
        .with_response("DeleteTopic", DeleteTopicResponse::default());

    let request = DeleteTopicRequest::default();
    let result = mock.delete_topic(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteTopic"));
}

#[tokio::test]
async fn pubsub_list_topics_with_mock() {
    let mock = PubsubClientMock::new()
        .with_response("ListTopics", ListTopicsResponse::default());

    let request = ListTopicsRequest::default();
    let result = mock.list_topics(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("ListTopics"));
}

#[tokio::test]
async fn pubsub_publish_with_mock() {
    let mock = PubsubClientMock::new()
        .with_response("Publish", PublishResponse::default());

    let request = PublishRequest::default();
    let result = mock.publish(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("Publish"));
}

#[tokio::test]
async fn pubsub_create_subscription_with_mock() {
    let mock = PubsubClientMock::new()
        .with_response("CreateSubscription", CreateSubscriptionResponse::default());

    let request = CreateSubscriptionRequest::default();
    let result = mock.create_subscription(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("CreateSubscription"));
}

#[tokio::test]
async fn pubsub_pull_with_mock() {
    let mock = PubsubClientMock::new()
        .with_response("Pull", PullResponse::default());

    let request = PullRequest::default();
    let result = mock.pull(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("Pull"));
}

