//! Tests for Gcp Cloud Storage client.
//!
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use crate::api::gcp::storage::*;
use crate::api::mocks::gcp::StorageClientMock;

#[test]
fn storage_client_can_be_created() {
    let client = StorageClient::new();
    // Client should be created successfully
}

#[test]
fn storage_client_with_custom_base_url() {
    let client = StorageClient::with_base_url("http://custom:8080");
    // Client should accept custom base URL
}

#[tokio::test]
async fn storage_create_bucket_with_mock() {
    let mock = StorageClientMock::new()
        .with_response("CreateBucket", CreateBucketResponse::default());

    let request = CreateBucketRequest::default();
    let result = mock.create_bucket(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("CreateBucket"));
}

#[tokio::test]
async fn storage_delete_bucket_with_mock() {
    let mock = StorageClientMock::new()
        .with_response("DeleteBucket", DeleteBucketResponse::default());

    let request = DeleteBucketRequest::default();
    let result = mock.delete_bucket(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteBucket"));
}

#[tokio::test]
async fn storage_list_buckets_with_mock() {
    let mock = StorageClientMock::new()
        .with_response("ListBuckets", ListBucketsResponse::default());

    let request = ListBucketsRequest::default();
    let result = mock.list_buckets(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("ListBuckets"));
}

#[tokio::test]
async fn storage_upload_object_with_mock() {
    let mock = StorageClientMock::new()
        .with_response("UploadObject", UploadObjectResponse::default());

    let request = UploadObjectRequest::default();
    let result = mock.upload_object(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("UploadObject"));
}

#[tokio::test]
async fn storage_download_object_with_mock() {
    let mock = StorageClientMock::new()
        .with_response("DownloadObject", DownloadObjectResponse::default());

    let request = DownloadObjectRequest::default();
    let result = mock.download_object(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DownloadObject"));
}

#[tokio::test]
async fn storage_delete_object_with_mock() {
    let mock = StorageClientMock::new()
        .with_response("DeleteObject", DeleteObjectResponse::default());

    let request = DeleteObjectRequest::default();
    let result = mock.delete_object(request).await;

    assert!(result.is_ok());
    assert!(mock.was_called("DeleteObject"));
}

