//! IAC Modules Page Tests
//!
//! Generated by `rsc scaffold routes`

use rsc::test::*;

// ============================================================================
// PAGE RENDER TESTS
// ============================================================================

#[test]
fn iac_modules_renders_without_error() {
    let result = render! {
        TestContextProvider {
            IacModulesPage()
        }
    };
    assert!(result.is_ok());
}

#[test]
fn iac_modules_displays_title() {
    let rendered = render! {
        TestContextProvider {
            IacModulesPage()
        }
    };
    assert!(rendered.contains_text("Modules"));
}

// ============================================================================
// MODULE GRID COMPONENT TESTS
// ============================================================================

#[test]
fn module_grid_renders() {
    let rendered = render! {
        TestContextProvider {
            ModuleGrid()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn module_grid_shows_loading() {
    let rendered = render! {
        TestContextProvider {
            ModuleGrid()
        }
    };
    assert!(rendered.contains_text("Loading") || rendered.query_selector(".loading").is_some());
}

#[test]
fn module_grid_displays_modules() {
    let rendered = render_with_mock! {
        data: [
            { id: "vpc", name: "VPC", version: "1.0.0" },
            { id: "eks", name: "EKS Cluster", version: "2.1.0" },
            { id: "rds", name: "RDS Database", version: "1.5.0" },
        ],
        ModuleGrid()
    };
    let items = rendered.query_selector_all("li, .module-card");
    assert!(items.len() >= 3);
}

#[test]
fn module_grid_items_are_links() {
    let rendered = render_with_mock! {
        data: [{ id: "vpc", name: "VPC" }],
        ModuleGrid()
    };
    let links = rendered.query_selector_all("a[href*='/iac/modules/']");
    assert!(links.len() > 0);
}

// ============================================================================
// MODULE SEARCH COMPONENT TESTS
// ============================================================================

#[test]
fn module_search_renders() {
    let rendered = render! {
        TestContextProvider {
            ModuleSearch()
        }
    };
    assert!(rendered.query_selector("form, .form-container").is_some());
}

#[test]
fn module_search_has_input() {
    let rendered = render! {
        TestContextProvider {
            ModuleSearch()
        }
    };
    let input = rendered.query_selector("input[type='search'], input[name='search']");
    assert!(input.is_some());
}

#[test]
fn module_search_filters_results() {
    let rendered = render! {
        TestContextProvider {
            IacModulesPage()
        }
    };

    // Type in search
    let input = rendered.query_selector("input[type='search']");
    if let Some(input) = input {
        input.fire_event("input", |e| e.value = "vpc");
    }

    assert!(rendered.is_ok());
}

// ============================================================================
// MODULE DETAIL TESTS
// ============================================================================

#[test]
fn iac_module_detail_renders() {
    let result = render! {
        TestContextProvider {
            IacModuleDetailPage(module: "vpc".to_string())
        }
    };
    assert!(result.is_ok());
}

#[test]
fn module_header_shows_name() {
    let rendered = render_with_mock! {
        module: { id: "vpc", name: "VPC", version: "1.0.0" },
        ModuleHeader()
    };
    assert!(rendered.contains_text("VPC") || rendered.contains_text("vpc"));
}

#[test]
fn module_header_shows_version() {
    let rendered = render_with_mock! {
        module: { id: "vpc", name: "VPC", version: "1.0.0" },
        ModuleHeader()
    };
    assert!(rendered.contains_text("1.0.0") || rendered.contains_text("version"));
}

#[test]
fn module_variables_renders() {
    let rendered = render! {
        TestContextProvider {
            ModuleVariables()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn module_outputs_renders() {
    let rendered = render! {
        TestContextProvider {
            ModuleOutputs()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn module_usage_renders() {
    let rendered = render! {
        ModuleUsage()
    };
    assert!(rendered.query_selector(".component").is_some());
}

#[test]
fn module_usage_shows_code_example() {
    let rendered = render_with_mock! {
        module: { id: "vpc" },
        ModuleUsage()
    };
    let code = rendered.query_selector("pre, code");
    assert!(code.is_some() || rendered.contains_text("module"));
}

// ============================================================================
// HELPER
// ============================================================================

#[component]
fn TestContextProvider(children: Children) -> Element {
    use @modules::context::AppContextProvider;
    rsx! { AppContextProvider { {children} } }
}
