//! IAC Landing Page Tests
//!
//! Generated by `rsc scaffold routes`

use rsc::test::*;

// ============================================================================
// PAGE RENDER TESTS
// ============================================================================

#[test]
fn iac_landing_renders_without_error() {
    let result = render! {
        TestContextProvider {
            IacLandingPage()
        }
    };
    assert!(result.is_ok());
}

#[test]
fn iac_landing_displays_title() {
    let rendered = render! {
        TestContextProvider {
            IacLandingPage()
        }
    };
    assert!(rendered.contains_text("Infrastructure") || rendered.contains_text("IAC"));
}

// ============================================================================
// IAC OVERVIEW COMPONENT TESTS
// ============================================================================

#[test]
fn iac_overview_renders() {
    let rendered = render! {
        TestContextProvider {
            IacOverview()
        }
    };
    assert!(rendered.query_selector(".container").is_some());
}

#[test]
fn iac_overview_shows_features() {
    let rendered = render! {
        TestContextProvider {
            IacOverview()
        }
    };
    assert!(rendered.contains_text("Modules") ||
            rendered.contains_text("Deploy") ||
            rendered.contains_text("State"));
}

// ============================================================================
// DEPLOYMENT STATUS COMPONENT TESTS
// ============================================================================

#[test]
fn deployment_status_renders() {
    let rendered = render! {
        DeploymentStatus()
    };
    assert!(rendered.query_selector(".component").is_some());
}

#[test]
fn deployment_status_shows_current_state() {
    let rendered = render_with_mock! {
        status: { state: "idle", lastDeployment: "2024-01-15T10:00:00Z" },
        DeploymentStatus()
    };
    assert!(rendered.contains_text("idle") ||
            rendered.contains_text("Ready") ||
            rendered.contains_text("Last"));
}

// ============================================================================
// PENDING CHANGES COMPONENT TESTS
// ============================================================================

#[test]
fn pending_changes_renders() {
    let rendered = render! {
        TestContextProvider {
            PendingChanges()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn pending_changes_shows_empty_state() {
    let rendered = render_with_mock! {
        data: [],
        PendingChanges()
    };
    assert!(rendered.contains_text("No") || rendered.query_selector(".empty-state").is_some());
}

#[test]
fn pending_changes_displays_items() {
    let rendered = render_with_mock! {
        data: [
            { id: "1", type: "add", resource: "aws_s3_bucket.main" },
            { id: "2", type: "change", resource: "aws_lambda_function.api" },
        ],
        PendingChanges()
    };
    let items = rendered.query_selector_all("li, .change-item");
    assert!(items.len() >= 2);
}

// ============================================================================
// NAVIGATION TESTS
// ============================================================================

#[test]
fn iac_landing_has_modules_link() {
    let rendered = render! {
        TestContextProvider {
            IacLandingPage()
        }
    };
    let link = rendered.query_selector("a[href='/iac/modules']");
    assert!(link.is_some());
}

#[test]
fn iac_landing_has_deploy_link() {
    let rendered = render! {
        TestContextProvider {
            IacLandingPage()
        }
    };
    let link = rendered.query_selector("a[href='/iac/deploy']");
    assert!(link.is_some());
}

#[test]
fn iac_landing_has_state_link() {
    let rendered = render! {
        TestContextProvider {
            IacLandingPage()
        }
    };
    let link = rendered.query_selector("a[href='/iac/state']");
    assert!(link.is_some());
}

// ============================================================================
// HELPER
// ============================================================================

#[component]
fn TestContextProvider(children: Children) -> Element {
    use crate::modules::context::AppContextProvider;
    rsx! { AppContextProvider { {children} } }
}
