//! CloudEmu Landing Page Tests
//!
//! Generated by `rsc scaffold routes`

use rsc::test::*;

// ============================================================================
// PAGE RENDER TESTS
// ============================================================================

#[test]
fn cloudemu_landing_renders_without_error() {
    let result = render! {
        TestContextProvider {
            CloudemuLandingPage()
        }
    };
    assert!(result.is_ok());
}

#[test]
fn cloudemu_landing_has_correct_title() {
    let rendered = render! {
        TestContextProvider {
            CloudemuLandingPage()
        }
    };
    assert!(rendered.contains_text("CloudEmu"));
}

// ============================================================================
// PROVIDER OVERVIEW COMPONENT TESTS
// ============================================================================

#[test]
fn provider_overview_renders() {
    let rendered = render! {
        TestContextProvider {
            ProviderOverview()
        }
    };
    assert!(rendered.query_selector(".container").is_some());
}

#[test]
fn provider_overview_shows_active_providers() {
    let rendered = render! {
        TestContextProvider {
            ProviderOverview()
        }
    };
    // Should show at least AWS, Azure, GCP
    assert!(rendered.contains_text("AWS") || rendered.query_selector("[data-provider]").is_some());
}

#[test]
fn provider_overview_has_state_management() {
    let rendered = render! {
        TestContextProvider {
            ProviderOverview()
        }
    };
    // Container components should have state
    assert!(rendered.is_ok());
}

// ============================================================================
// SERVICE HEALTH GRID COMPONENT TESTS
// ============================================================================

#[test]
fn service_health_grid_renders() {
    let rendered = render! {
        TestContextProvider {
            ServiceHealthGrid()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn service_health_grid_shows_loading_state() {
    let rendered = render! {
        TestContextProvider {
            ServiceHealthGrid()
        }
    };
    // List components show loading initially
    assert!(rendered.contains_text("Loading") || rendered.query_selector(".loading").is_some());
}

#[test]
fn service_health_grid_shows_empty_state() {
    let rendered = render_with_mock! {
        data: [],
        ServiceHealthGrid()
    };
    assert!(rendered.contains_text("No items") || rendered.query_selector(".empty-state").is_some());
}

#[test]
fn service_health_grid_displays_items() {
    let rendered = render_with_mock! {
        data: [
            { name: "S3", status: "healthy" },
            { name: "DynamoDB", status: "healthy" },
        ],
        ServiceHealthGrid()
    };
    let items = rendered.query_selector_all(".item-list li, .health-item");
    assert!(items.len() >= 2);
}

// ============================================================================
// REQUEST ACTIVITY CHART COMPONENT TESTS
// ============================================================================

#[test]
fn request_activity_chart_renders() {
    let rendered = render! {
        TestContextProvider {
            RequestActivityChart()
        }
    };
    assert!(rendered.query_selector(".component").is_some());
}

#[test]
fn request_activity_chart_displays_content() {
    let rendered = render! {
        TestContextProvider {
            RequestActivityChart()
        }
    };
    assert!(rendered.is_ok());
}

// ============================================================================
// NAVIGATION TESTS
// ============================================================================

#[test]
fn cloudemu_landing_has_provider_links() {
    let rendered = render! {
        TestContextProvider {
            CloudemuLandingPage()
        }
    };
    // Should have links to provider pages
    let links = rendered.query_selector_all("a[href^='/cloudemu/']");
    assert!(links.len() > 0);
}

#[test]
fn cloudemu_landing_has_logs_link() {
    let rendered = render! {
        TestContextProvider {
            CloudemuLandingPage()
        }
    };
    let logs_link = rendered.query_selector("a[href='/cloudemu/logs']");
    assert!(logs_link.is_some());
}

// ============================================================================
// CONTEXT INTEGRATION TESTS
// ============================================================================

#[test]
fn cloudemu_landing_respects_provider_context() {
    let rendered = render_with_context! {
        provider: "aws",
        CloudemuLandingPage()
    };
    // AWS should be highlighted or selected
    assert!(rendered.is_ok());
}

#[test]
fn cloudemu_landing_updates_on_provider_change() {
    let mut context = TestContext::new();
    let rendered = render_with_context!(context, CloudemuLandingPage());

    context.set_provider("azure");

    // UI should update
    assert!(rendered.is_ok());
}

// ============================================================================
// HELPER
// ============================================================================

#[component]
fn TestContextProvider(children: Children) -> Element {
    use crate::modules::context::AppContextProvider;
    rsx! { AppContextProvider { {children} } }
}
