//! CloudEmu Service Detail Page Tests
//!
//! Generated by `rsc scaffold routes`

use rsc::test::*;

// ============================================================================
// PAGE RENDER TESTS
// ============================================================================

#[test]
fn cloudemu_service_detail_renders_without_error() {
    let result = render! {
        TestContextProvider {
            CloudemuServiceDetailPage(
                provider: "aws".to_string(),
                service: "s3".to_string(),
                id: "my-bucket".to_string()
            )
        }
    };
    assert!(result.is_ok());
}

#[test]
fn cloudemu_service_detail_displays_resource_id() {
    let rendered = render! {
        TestContextProvider {
            CloudemuServiceDetailPage(
                provider: "aws".to_string(),
                service: "s3".to_string(),
                id: "my-bucket".to_string()
            )
        }
    };
    assert!(rendered.contains_text("my-bucket"));
}

// ============================================================================
// RESOURCE DETAIL HEADER COMPONENT TESTS
// ============================================================================

#[test]
fn resource_detail_header_renders() {
    let rendered = render! {
        ResourceDetailHeader()
    };
    assert!(rendered.query_selector(".component").is_some());
}

#[test]
fn resource_detail_header_shows_actions() {
    let rendered = render! {
        ResourceDetailHeader()
    };
    let actions = rendered.query_selector_all("button, a.action");
    assert!(actions.len() > 0);
}

// ============================================================================
// RESOURCE PROPERTIES COMPONENT TESTS
// ============================================================================

#[test]
fn resource_properties_renders() {
    let rendered = render! {
        ResourceProperties()
    };
    assert!(rendered.query_selector(".component").is_some());
}

#[test]
fn resource_properties_displays_data() {
    let rendered = render_with_mock! {
        data: {
            name: "my-bucket",
            region: "us-east-1",
            created: "2024-01-15"
        },
        ResourceProperties()
    };
    assert!(rendered.contains_text("my-bucket") || rendered.contains_text("region"));
}

// ============================================================================
// RESOURCE OPERATIONS COMPONENT TESTS
// ============================================================================

#[test]
fn resource_operations_renders() {
    let rendered = render! {
        TestContextProvider {
            ResourceOperations()
        }
    };
    assert!(rendered.query_selector(".container").is_some());
}

#[test]
fn resource_operations_shows_available_ops() {
    let rendered = render_with_mock! {
        operations: ["GetObject", "PutObject", "DeleteObject"],
        ResourceOperations()
    };
    let ops = rendered.query_selector_all("button, .operation-item");
    assert!(ops.len() > 0);
}

// ============================================================================
// DELETE RESOURCE MODAL COMPONENT TESTS
// ============================================================================

#[test]
fn delete_resource_modal_renders() {
    let rendered = render! {
        DeleteResourceModal()
    };
    // Modal may be hidden by default
    assert!(rendered.is_ok());
}

#[test]
fn delete_resource_modal_has_confirm_button() {
    let rendered = render_with_state! {
        is_open: true,
        DeleteResourceModal()
    };
    let confirm = rendered.query_selector("button.confirm, button[data-action='delete']");
    assert!(confirm.is_some() || rendered.contains_text("Delete") || rendered.contains_text("Confirm"));
}

#[test]
fn delete_resource_modal_has_cancel_button() {
    let rendered = render_with_state! {
        is_open: true,
        DeleteResourceModal()
    };
    let cancel = rendered.query_selector("button.cancel, button[data-action='cancel']");
    assert!(cancel.is_some() || rendered.contains_text("Cancel"));
}

// ============================================================================
// OPERATIONS TESTS
// ============================================================================

#[test]
fn service_detail_can_trigger_delete() {
    let rendered = render! {
        TestContextProvider {
            CloudemuServiceDetailPage(
                provider: "aws".to_string(),
                service: "s3".to_string(),
                id: "test-bucket".to_string()
            )
        }
    };
    let delete_btn = rendered.query_selector("button[data-action='delete'], button.delete-btn");
    assert!(delete_btn.is_some() || rendered.contains_text("Delete"));
}

// ============================================================================
// NAVIGATION TESTS
// ============================================================================

#[test]
fn service_detail_has_back_to_list() {
    let rendered = render! {
        TestContextProvider {
            CloudemuServiceDetailPage(
                provider: "aws".to_string(),
                service: "s3".to_string(),
                id: "my-bucket".to_string()
            )
        }
    };
    let back_link = rendered.query_selector("a[href='/cloudemu/aws/s3']");
    assert!(back_link.is_some());
}

// ============================================================================
// HELPER
// ============================================================================

#[component]
fn TestContextProvider(children: Children) -> Element {
    use @modules::context::AppContextProvider;
    rsx! { AppContextProvider { {children} } }
}
