//! CloudEmu Service Page Tests
//!
//! Generated by `rsc scaffold routes`

use rsc::test::*;

// ============================================================================
// PAGE RENDER TESTS
// ============================================================================

#[test]
fn cloudemu_service_renders_without_error() {
    let result = render! {
        TestContextProvider {
            CloudemuServicePage(provider: "aws".to_string(), service: "s3".to_string())
        }
    };
    assert!(result.is_ok());
}

#[test]
fn cloudemu_service_displays_service_name() {
    let rendered = render! {
        TestContextProvider {
            CloudemuServicePage(provider: "aws".to_string(), service: "s3".to_string())
        }
    };
    assert!(rendered.contains_text("S3") || rendered.contains_text("s3"));
}

// ============================================================================
// SERVICE HEADER COMPONENT TESTS
// ============================================================================

#[test]
fn service_header_renders() {
    let rendered = render! {
        ServiceHeader(provider: "aws".to_string(), service: "s3".to_string())
    };
    assert!(rendered.query_selector(".component").is_some());
}

#[test]
fn service_header_displays_provider() {
    let rendered = render! {
        ServiceHeader(provider: "aws".to_string(), service: "dynamodb".to_string())
    };
    assert!(rendered.contains_text("aws") || rendered.contains_text("AWS"));
}

#[test]
fn service_header_displays_service() {
    let rendered = render! {
        ServiceHeader(provider: "aws".to_string(), service: "dynamodb".to_string())
    };
    assert!(rendered.contains_text("dynamodb") || rendered.contains_text("DynamoDB"));
}

#[test]
fn service_header_has_breadcrumb() {
    let rendered = render! {
        ServiceHeader(provider: "aws".to_string(), service: "s3".to_string())
    };
    // Should have breadcrumb navigation
    let breadcrumb = rendered.query_selector(".breadcrumb, nav[aria-label='breadcrumb']");
    assert!(breadcrumb.is_some() || rendered.contains_text("/") || rendered.contains_text(">"));
}

// ============================================================================
// RESOURCE LIST COMPONENT TESTS
// ============================================================================

#[test]
fn resource_list_renders() {
    let rendered = render! {
        TestContextProvider {
            ResourceList()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn resource_list_shows_loading_state() {
    let rendered = render! {
        TestContextProvider {
            ResourceList()
        }
    };
    assert!(rendered.contains_text("Loading") || rendered.query_selector(".loading").is_some());
}

#[test]
fn resource_list_shows_empty_state() {
    let rendered = render_with_mock! {
        data: [],
        ResourceList()
    };
    assert!(rendered.contains_text("No items") || rendered.query_selector(".empty-state").is_some());
}

#[test]
fn resource_list_displays_resources() {
    let rendered = render_with_mock! {
        data: [
            { id: "bucket-1", name: "my-bucket" },
            { id: "bucket-2", name: "data-bucket" },
        ],
        ResourceList()
    };
    let items = rendered.query_selector_all("li, .resource-item");
    assert!(items.len() >= 2);
}

#[test]
fn resource_list_items_are_clickable() {
    let rendered = render_with_mock! {
        provider: "aws",
        service: "s3",
        data: [{ id: "bucket-1", name: "my-bucket" }],
        ResourceList()
    };
    let clickable = rendered.query_selector_all("a, button, [role='button']");
    assert!(clickable.len() > 0);
}

// ============================================================================
// RESOURCE FILTERS COMPONENT TESTS
// ============================================================================

#[test]
fn resource_filters_renders() {
    let rendered = render! {
        TestContextProvider {
            ResourceFilters()
        }
    };
    assert!(rendered.query_selector(".form-container, form").is_some());
}

#[test]
fn resource_filters_has_input_fields() {
    let rendered = render! {
        TestContextProvider {
            ResourceFilters()
        }
    };
    let inputs = rendered.query_selector_all("input, select");
    assert!(inputs.len() > 0);
}

#[test]
fn resource_filters_has_submit_button() {
    let rendered = render! {
        TestContextProvider {
            ResourceFilters()
        }
    };
    let submit = rendered.query_selector("button[type='submit'], button.filter-btn");
    assert!(submit.is_some());
}

// ============================================================================
// CREATE RESOURCE BUTTON COMPONENT TESTS
// ============================================================================

#[test]
fn create_resource_button_renders() {
    let rendered = render! {
        CreateResourceButton()
    };
    assert!(rendered.query_selector(".component, button, a").is_some());
}

#[test]
fn create_resource_button_is_link_to_new() {
    let rendered = render_with_context! {
        provider: "aws",
        service: "s3",
        CreateResourceButton()
    };
    let link = rendered.query_selector("a[href*='/new']");
    assert!(link.is_some());
}

// ============================================================================
// SERVICE SPECIFIC TESTS
// ============================================================================

#[test]
fn s3_service_shows_buckets() {
    let rendered = render! {
        TestContextProvider {
            CloudemuServicePage(provider: "aws".to_string(), service: "s3".to_string())
        }
    };
    assert!(rendered.contains_text("bucket") || rendered.contains_text("Bucket"));
}

#[test]
fn dynamodb_service_shows_tables() {
    let rendered = render! {
        TestContextProvider {
            CloudemuServicePage(provider: "aws".to_string(), service: "dynamodb".to_string())
        }
    };
    assert!(rendered.is_ok());
}

#[test]
fn lambda_service_shows_functions() {
    let rendered = render! {
        TestContextProvider {
            CloudemuServicePage(provider: "aws".to_string(), service: "lambda".to_string())
        }
    };
    assert!(rendered.is_ok());
}

// ============================================================================
// NAVIGATION TESTS
// ============================================================================

#[test]
fn service_page_has_back_to_provider() {
    let rendered = render! {
        TestContextProvider {
            CloudemuServicePage(provider: "aws".to_string(), service: "s3".to_string())
        }
    };
    let back_link = rendered.query_selector("a[href='/cloudemu/aws']");
    assert!(back_link.is_some());
}

#[test]
fn service_page_has_resource_detail_links() {
    let rendered = render_with_mock! {
        provider: "aws",
        service: "s3",
        data: [{ id: "bucket-1" }],
        CloudemuServicePage(provider: "aws".to_string(), service: "s3".to_string())
    };
    let detail_links = rendered.query_selector_all("a[href*='/cloudemu/aws/s3/']");
    assert!(detail_links.len() > 0);
}

// ============================================================================
// HELPER
// ============================================================================

#[component]
fn TestContextProvider(children: Children) -> Element {
    use crate::modules::context::AppContextProvider;
    rsx! { AppContextProvider { {children} } }
}
