//! CloudEmu Provider Page Tests
//!
//! Generated by `rsc scaffold routes`

use rsc::test::*;

// ============================================================================
// PAGE RENDER TESTS
// ============================================================================

#[test]
fn cloudemu_provider_renders_without_error() {
    let result = render! {
        TestContextProvider {
            CloudemuProviderPage(provider: "aws".to_string())
        }
    };
    assert!(result.is_ok());
}

#[test]
fn cloudemu_provider_displays_provider_name() {
    let rendered = render! {
        TestContextProvider {
            CloudemuProviderPage(provider: "aws".to_string())
        }
    };
    assert!(rendered.contains_text("AWS"));
}

// ============================================================================
// PROVIDER HEADER COMPONENT TESTS
// ============================================================================

#[test]
fn provider_header_renders() {
    let rendered = render! {
        ProviderHeader(provider: "aws".to_string())
    };
    assert!(rendered.query_selector(".component").is_some());
}

#[test]
fn provider_header_displays_provider_prop() {
    let rendered = render! {
        ProviderHeader(provider: "azure".to_string())
    };
    assert!(rendered.contains_text("azure") || rendered.contains_text("Azure"));
}

#[test]
fn provider_header_shows_stats() {
    let rendered = render! {
        ProviderHeader(provider: "aws".to_string())
    };
    // Header should show provider stats
    assert!(rendered.is_ok());
}

// ============================================================================
// SERVICE GRID COMPONENT TESTS
// ============================================================================

#[test]
fn service_grid_renders() {
    let rendered = render! {
        TestContextProvider {
            ServiceGrid()
        }
    };
    assert!(rendered.query_selector(".list-container").is_some());
}

#[test]
fn service_grid_shows_loading_state() {
    let rendered = render! {
        TestContextProvider {
            ServiceGrid()
        }
    };
    assert!(rendered.contains_text("Loading") || rendered.query_selector(".loading").is_some());
}

#[test]
fn service_grid_displays_services() {
    let rendered = render_with_mock! {
        data: [
            { id: "s3", name: "S3", icon: "bucket" },
            { id: "dynamodb", name: "DynamoDB", icon: "database" },
            { id: "lambda", name: "Lambda", icon: "function" },
        ],
        ServiceGrid()
    };
    let items = rendered.query_selector_all("li, .service-card");
    assert!(items.len() >= 3);
}

#[test]
fn service_grid_items_are_links() {
    let rendered = render_with_mock! {
        provider: "aws",
        data: [{ id: "s3", name: "S3" }],
        ServiceGrid()
    };
    let links = rendered.query_selector_all("a[href*='/s3']");
    assert!(links.len() > 0);
}

// ============================================================================
// QUICK ACTIONS COMPONENT TESTS
// ============================================================================

#[test]
fn quick_actions_renders() {
    let rendered = render! {
        TestContextProvider {
            QuickActions()
        }
    };
    assert!(rendered.query_selector(".container").is_some());
}

#[test]
fn quick_actions_has_action_buttons() {
    let rendered = render! {
        TestContextProvider {
            QuickActions()
        }
    };
    let buttons = rendered.query_selector_all("button, a.action");
    assert!(buttons.len() > 0);
}

// ============================================================================
// PROVIDER SWITCHING TESTS
// ============================================================================

#[test]
fn provider_page_updates_for_aws() {
    let rendered = render! {
        TestContextProvider {
            CloudemuProviderPage(provider: "aws".to_string())
        }
    };
    assert!(rendered.contains_text("AWS") || rendered.contains_text("S3"));
}

#[test]
fn provider_page_updates_for_azure() {
    let rendered = render! {
        TestContextProvider {
            CloudemuProviderPage(provider: "azure".to_string())
        }
    };
    assert!(rendered.contains_text("Azure") || rendered.contains_text("Blob"));
}

#[test]
fn provider_page_updates_for_gcp() {
    let rendered = render! {
        TestContextProvider {
            CloudemuProviderPage(provider: "gcp".to_string())
        }
    };
    assert!(rendered.contains_text("GCP") || rendered.contains_text("Storage"));
}

// ============================================================================
// NAVIGATION TESTS
// ============================================================================

#[test]
fn provider_page_has_service_links() {
    let rendered = render! {
        TestContextProvider {
            CloudemuProviderPage(provider: "aws".to_string())
        }
    };
    let links = rendered.query_selector_all("a[href*='/cloudemu/aws/']");
    assert!(links.len() > 0);
}

#[test]
fn provider_page_has_back_link() {
    let rendered = render! {
        TestContextProvider {
            CloudemuProviderPage(provider: "aws".to_string())
        }
    };
    let back_link = rendered.query_selector("a[href='/cloudemu']");
    assert!(back_link.is_some());
}

// ============================================================================
// HELPER
// ============================================================================

#[component]
fn TestContextProvider(children: Children) -> Element {
    use crate::modules::context::AppContextProvider;
    rsx! { AppContextProvider { {children} } }
}
