//! CloudEmu Service New (Create Resource) Page Tests
//!
//! Generated by `rsc scaffold routes`

use rsc::test::*;

// ============================================================================
// PAGE RENDER TESTS
// ============================================================================

#[test]
fn cloudemu_service_new_renders_without_error() {
    let result = render! {
        TestContextProvider {
            CloudemuServiceNewPage(provider: "aws".to_string(), service: "s3".to_string())
        }
    };
    assert!(result.is_ok());
}

#[test]
fn cloudemu_service_new_displays_title() {
    let rendered = render! {
        TestContextProvider {
            CloudemuServiceNewPage(provider: "aws".to_string(), service: "s3".to_string())
        }
    };
    assert!(rendered.contains_text("Create") || rendered.contains_text("New"));
}

// ============================================================================
// RESOURCE FORM COMPONENT TESTS
// ============================================================================

#[test]
fn resource_form_renders() {
    let on_submit = |_| {};
    let rendered = render! {
        ResourceForm(service: "s3".to_string(), onSubmit: on_submit)
    };
    assert!(rendered.query_selector("form, .form-container").is_some());
}

#[test]
fn resource_form_has_required_fields() {
    let on_submit = |_| {};
    let rendered = render! {
        ResourceForm(service: "s3".to_string(), onSubmit: on_submit)
    };
    let inputs = rendered.query_selector_all("input, select, textarea");
    assert!(inputs.len() > 0);
}

#[test]
fn resource_form_has_submit_button() {
    let on_submit = |_| {};
    let rendered = render! {
        ResourceForm(service: "s3".to_string(), onSubmit: on_submit)
    };
    let submit = rendered.query_selector("button[type='submit']");
    assert!(submit.is_some());
}

#[test]
fn resource_form_shows_submitting_state() {
    let on_submit = |_| {};
    let rendered = render_with_state! {
        submitting: true,
        ResourceForm(service: "s3".to_string(), onSubmit: on_submit)
    };
    assert!(rendered.contains_text("Submitting") || rendered.query_selector("button[disabled]").is_some());
}

#[test]
fn resource_form_validates_input() {
    let on_submit = |_| {};
    let rendered = render! {
        ResourceForm(service: "s3".to_string(), onSubmit: on_submit)
    };

    // Try to submit empty form
    rendered.fire_event("form", "submit");

    // Should show validation errors or prevent submission
    assert!(rendered.is_ok());
}

// ============================================================================
// FORM PREVIEW COMPONENT TESTS
// ============================================================================

#[test]
fn form_preview_renders() {
    let rendered = render! {
        FormPreview()
    };
    assert!(rendered.query_selector(".component").is_some());
}

#[test]
fn form_preview_shows_resource_data() {
    let rendered = render_with_mock! {
        form_data: { name: "my-bucket", region: "us-east-1" },
        FormPreview()
    };
    assert!(rendered.contains_text("my-bucket") || rendered.contains_text("region"));
}

// ============================================================================
// SERVICE-SPECIFIC FORM TESTS
// ============================================================================

#[test]
fn s3_form_has_bucket_name_field() {
    let on_submit = |_| {};
    let rendered = render! {
        ResourceForm(service: "s3".to_string(), onSubmit: on_submit)
    };
    let name_field = rendered.query_selector("input[name='bucket_name'], input[name='name']");
    assert!(name_field.is_some());
}

#[test]
fn s3_form_has_region_field() {
    let on_submit = |_| {};
    let rendered = render! {
        ResourceForm(service: "s3".to_string(), onSubmit: on_submit)
    };
    let region_field = rendered.query_selector("select[name='region'], input[name='region']");
    assert!(region_field.is_some() || rendered.contains_text("region"));
}

#[test]
fn dynamodb_form_has_table_name_field() {
    let on_submit = |_| {};
    let rendered = render! {
        ResourceForm(service: "dynamodb".to_string(), onSubmit: on_submit)
    };
    let name_field = rendered.query_selector("input[name='table_name'], input[name='name']");
    assert!(name_field.is_some());
}

// ============================================================================
// NAVIGATION TESTS
// ============================================================================

#[test]
fn service_new_has_cancel_link() {
    let rendered = render! {
        TestContextProvider {
            CloudemuServiceNewPage(provider: "aws".to_string(), service: "s3".to_string())
        }
    };
    let cancel = rendered.query_selector("a[href='/cloudemu/aws/s3'], button.cancel");
    assert!(cancel.is_some() || rendered.contains_text("Cancel"));
}

// ============================================================================
// HELPER
// ============================================================================

#[component]
fn TestContextProvider(children: Children) -> Element {
    use @modules::context::AppContextProvider;
    rsx! { AppContextProvider { {children} } }
}
