//! Cloudkit API tests.
//!
//! API integration tests for cloudkit feature.
//! Generated by `rsc scaffold services`

use rustscript::test::*;
use rustscript::http::*;
use crate::api::*;

#[tokio::test]
async fn cloudkit_api_client_initializes() {
    let client = CloudkitClient::new();
    assert!(client.is_ready().await);
}

#[tokio::test]
async fn cloudkit_list_resources() {
    let client = CloudkitClient::new();
    let mock = CloudkitClientMock::new()
        .with_response("list", vec![]);

    let result = mock.list(Default::default()).await;
    assert!(result.is_ok());
}

#[tokio::test]
async fn cloudkit_get_resource() {
    let mock = CloudkitClientMock::new()
        .with_response("get", Default::default());

    let result = mock.get("test-id".to_string()).await;
    assert!(result.is_ok());
}

#[tokio::test]
async fn cloudkit_create_resource() {
    let mock = CloudkitClientMock::new()
        .with_response("create", Default::default());

    let result = mock.create(Default::default()).await;
    assert!(result.is_ok());
    assert!(mock.was_called("create"));
}

#[tokio::test]
async fn cloudkit_delete_resource() {
    let mock = CloudkitClientMock::new()
        .with_response("delete", ());

    let result = mock.delete("test-id".to_string()).await;
    assert!(result.is_ok());
}

#[tokio::test]
async fn cloudkit_handles_api_error() {
    let mock = CloudkitClientMock::new()
        .with_error("get", ApiError::NotFound);

    let result = mock.get("nonexistent".to_string()).await;
    assert!(result.is_err());
}
